module.exports = HELSEFORETAK = [
  'Helse Møre og Romsdal',
  'Helse Nord-Trøndelag',
  'St. Olavs hospital',
  'Finnmarkssykehuset HF',
  'Helgelandssykehuset HF',
  'Nordlandssykehuset HF',
  'Universitetssykehuset Nord-Norge HF',
  'Akershus universitetssykehus HF',
  'Oslo universitetssykehus HF',
  'Private med avtale med Helse Sør-Øst i Oslo',
  'Sørlandet sykehus HF',
  'Sunnaas Sykehus HF',
  'Sykehuset i Vestfold HF',
  'Sykehuset Innlandet HF',
  'Sykehuset Østfold HF',
  'Sykehuset Telemark HF',
  'Vestre Viken HF',
  'Helse Bergen HF + Privat med avtale med Helse Vest i Bergen',
  'Helse Fonna HF',
  'Helse Førde HF',
  'Helse Stavanger HF',
];
